version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: uiowa-backend
    ports:
      - "5291:80"
    volumes:
      - receipt-data:/app/Receipts
      - db-data:/app/Data
    networks:
      - uiowa-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: uiowa-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - uiowa-network
    environment:
      - API_URL=http://backend:80/api

networks:
  uiowa-network:
    driver: bridge

volumes:
  receipt-data:
    driver: local
  db-data:
    driver: local
